name: Contrast AI SmartFix
description: An action that creates AI-generated Pull Requests to remediate Contrast Security vulnerability findings.

runs:
  using: "composite"
  steps:
    - name: Run Python script
      run: python ${{ github.action_path }}/main.py
      shell: bash