name: Build and Test

on:
  push:
    branches:
      - '*' # Run on all branches
  pull_request:
    branches:
      - '*' # Run on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Enable built-in pip caching
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Run tests
        run: PYTHONPATH=${{ github.workspace }}/src python -m unittest discover -s test -p "test*.py"
        env:
          BUILD_COMMAND: "echo 'Mock build command for testing'"
          FORMATTING_COMMAND: "echo 'Mock formatting command for testing'"
          GITHUB_TOKEN: ${{ github.token }}
          CONTRAST_HOST: "https://mock.contrastsecurity.com"
          CONTRAST_ORG_ID: "mock-org-id"
          CONTRAST_APP_ID: "mock-app-id"
          CONTRAST_AUTHORIZATION_KEY: "mock-auth-key"
          CONTRAST_API_KEY: "mock-api-key"
          DEBUG_MODE: "true"