name: Build and Test

on:
  push:
    branches:
      - '*' # Run on all branches
  pull_request:
    branches:
      - '*' # Run on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r src/requirements.txt
      - name: Run tests
        run: cd ${{ github.workspace }} && PYTHONPATH=${{ github.workspace }}/src python -m unittest discover -s test -p "test*.py"